import "./globals.css";
import type { Metadata } from "next";
import type { JSX } from "react";
import { Suspense } from "react";
import Header from "./Header";
import { ClickiesContextProvider } from "@/shared";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body>
        <ClickiesContextProvider>
          <Header />
          <Suspense>{children}</Suspense>
        </ClickiesContextProvider>
      </body>
    </html>
  );
}
